/* This file is generated by glib-genmarshal, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */
#ifndef __BRASERO_MARSHAL_MARSHAL_H__
#define __BRASERO_MARSHAL_MARSHAL_H__

#include <glib-object.h>

G_BEGIN_DECLS

/* INT:VOID (/home/david/checkout/gnome/brasero/libbrasero-burn/libbrasero-marshal.list:1) */
extern
void brasero_marshal_INT__VOID (GClosure     *closure,
                                GValue       *return_value,
                                guint         n_param_values,
                                const GValue *param_values,
                                gpointer      invocation_hint,
                                gpointer      marshal_data);

/* INT:INT (/home/david/checkout/gnome/brasero/libbrasero-burn/libbrasero-marshal.list:2) */
extern
void brasero_marshal_INT__INT (GClosure     *closure,
                               GValue       *return_value,
                               guint         n_param_values,
                               const GValue *param_values,
                               gpointer      invocation_hint,
                               gpointer      marshal_data);

/* INT:STRING (/home/david/checkout/gnome/brasero/libbrasero-burn/libbrasero-marshal.list:3) */
extern
void brasero_marshal_INT__STRING (GClosure     *closure,
                                  GValue       *return_value,
                                  guint         n_param_values,
                                  const GValue *param_values,
                                  gpointer      invocation_hint,
                                  gpointer      marshal_data);

/* INT:OBJECT (/home/david/checkout/gnome/brasero/libbrasero-burn/libbrasero-marshal.list:4) */
extern
void brasero_marshal_INT__OBJECT (GClosure     *closure,
                                  GValue       *return_value,
                                  guint         n_param_values,
                                  const GValue *param_values,
                                  gpointer      invocation_hint,
                                  gpointer      marshal_data);

/* INT:INT,STRING (/home/david/checkout/gnome/brasero/libbrasero-burn/libbrasero-marshal.list:5) */
extern
void brasero_marshal_INT__INT_STRING (GClosure     *closure,
                                      GValue       *return_value,
                                      guint         n_param_values,
                                      const GValue *param_values,
                                      gpointer      invocation_hint,
                                      gpointer      marshal_data);

/* INT:OBJECT,INT,INT (/home/david/checkout/gnome/brasero/libbrasero-burn/libbrasero-marshal.list:6) */
extern
void brasero_marshal_INT__OBJECT_INT_INT (GClosure     *closure,
                                          GValue       *return_value,
                                          guint         n_param_values,
                                          const GValue *param_values,
                                          gpointer      invocation_hint,
                                          gpointer      marshal_data);

/* INT:POINTER,BOOLEAN (/home/david/checkout/gnome/brasero/libbrasero-burn/libbrasero-marshal.list:7) */
extern
void brasero_marshal_INT__POINTER_BOOLEAN (GClosure     *closure,
                                           GValue       *return_value,
                                           guint         n_param_values,
                                           const GValue *param_values,
                                           gpointer      invocation_hint,
                                           gpointer      marshal_data);

/* BOOLEAN:VOID (/home/david/checkout/gnome/brasero/libbrasero-burn/libbrasero-marshal.list:8) */
extern
void brasero_marshal_BOOLEAN__VOID (GClosure     *closure,
                                    GValue       *return_value,
                                    guint         n_param_values,
                                    const GValue *param_values,
                                    gpointer      invocation_hint,
                                    gpointer      marshal_data);

/* BOOLEAN:STRING (/home/david/checkout/gnome/brasero/libbrasero-burn/libbrasero-marshal.list:9) */
extern
void brasero_marshal_BOOLEAN__STRING (GClosure     *closure,
                                      GValue       *return_value,
                                      guint         n_param_values,
                                      const GValue *param_values,
                                      gpointer      invocation_hint,
                                      gpointer      marshal_data);

/* BOOLEAN:POINTER (/home/david/checkout/gnome/brasero/libbrasero-burn/libbrasero-marshal.list:10) */
extern
void brasero_marshal_BOOLEAN__POINTER (GClosure     *closure,
                                       GValue       *return_value,
                                       guint         n_param_values,
                                       const GValue *param_values,
                                       gpointer      invocation_hint,
                                       gpointer      marshal_data);

/* VOID:INT,STRING (/home/david/checkout/gnome/brasero/libbrasero-burn/libbrasero-marshal.list:11) */
extern
void brasero_marshal_VOID__INT_STRING (GClosure     *closure,
                                       GValue       *return_value,
                                       guint         n_param_values,
                                       const GValue *param_values,
                                       gpointer      invocation_hint,
                                       gpointer      marshal_data);

/* VOID:POINTER,STRING (/home/david/checkout/gnome/brasero/libbrasero-burn/libbrasero-marshal.list:12) */
extern
void brasero_marshal_VOID__POINTER_STRING (GClosure     *closure,
                                           GValue       *return_value,
                                           guint         n_param_values,
                                           const GValue *param_values,
                                           gpointer      invocation_hint,
                                           gpointer      marshal_data);

/* VOID:POINTER,POINTER (/home/david/checkout/gnome/brasero/libbrasero-burn/libbrasero-marshal.list:13) */
extern
void brasero_marshal_VOID__POINTER_POINTER (GClosure     *closure,
                                            GValue       *return_value,
                                            guint         n_param_values,
                                            const GValue *param_values,
                                            gpointer      invocation_hint,
                                            gpointer      marshal_data);

/* VOID:OBJECT,BOOLEAN (/home/david/checkout/gnome/brasero/libbrasero-burn/libbrasero-marshal.list:14) */
extern
void brasero_marshal_VOID__OBJECT_BOOLEAN (GClosure     *closure,
                                           GValue       *return_value,
                                           guint         n_param_values,
                                           const GValue *param_values,
                                           gpointer      invocation_hint,
                                           gpointer      marshal_data);

/* VOID:OBJECT,UINT (/home/david/checkout/gnome/brasero/libbrasero-burn/libbrasero-marshal.list:15) */
extern
void brasero_marshal_VOID__OBJECT_UINT (GClosure     *closure,
                                        GValue       *return_value,
                                        guint         n_param_values,
                                        const GValue *param_values,
                                        gpointer      invocation_hint,
                                        gpointer      marshal_data);

/* VOID:BOOLEAN,BOOLEAN (/home/david/checkout/gnome/brasero/libbrasero-burn/libbrasero-marshal.list:16) */
extern
void brasero_marshal_VOID__BOOLEAN_BOOLEAN (GClosure     *closure,
                                            GValue       *return_value,
                                            guint         n_param_values,
                                            const GValue *param_values,
                                            gpointer      invocation_hint,
                                            gpointer      marshal_data);

/* VOID:DOUBLE,DOUBLE,LONG (/home/david/checkout/gnome/brasero/libbrasero-burn/libbrasero-marshal.list:17) */
extern
void brasero_marshal_VOID__DOUBLE_DOUBLE_LONG (GClosure     *closure,
                                               GValue       *return_value,
                                               guint         n_param_values,
                                               const GValue *param_values,
                                               gpointer      invocation_hint,
                                               gpointer      marshal_data);

/* VOID:POINTER,UINT,POINTER (/home/david/checkout/gnome/brasero/libbrasero-burn/libbrasero-marshal.list:18) */
extern
void brasero_marshal_VOID__POINTER_UINT_POINTER (GClosure     *closure,
                                                 GValue       *return_value,
                                                 guint         n_param_values,
                                                 const GValue *param_values,
                                                 gpointer      invocation_hint,
                                                 gpointer      marshal_data);


G_END_DECLS

#endif /* __BRASERO_MARSHAL_MARSHAL_H__ */
